package com.example.modeling_tools.type;

public enum Category {
    GRAPHICAL_MODELING_TOOL,
    BUSINESS_TOOL,
    DRAWING_TOOL,
    TEXT_BASED_MODELING_TOOL,
    METAMODELING_TOOL,
    MIXED_TEXTUAL_AND_GRAPHICAL_MODELING_TOOL
}
